name: Netlify Deploy Log

on:
  push:
    branches:
      - main

jobs:
  log-netlify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Monitor Netlify Deploy
        run: |
          echo "Waiting for Netlify deployment to start..."
          
          while true; do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.NETLIFY_ACCESS_TOKEN }}" https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys?branch=main&per_page=1)
            deploy_id=$(echo $response | jq -r '.[0].id')
            status=$(echo $response | jq -r '.[0].state')
            
            if [ "$status" != "null" ]; then
              echo "Deployment started. Deploy ID: $deploy_id"
              break
            fi
            
            sleep 5
          done
          
          while true; do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.NETLIFY_ACCESS_TOKEN }}" https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys?branch=main&per_page=1)
            status=$(echo $response | jq -r '.[0].state')
            
            echo "Current status: $status"
            
            if [ "$status" == "ready" ]; then
              echo "Deployment completed successfully!"
              break
            elif [ "$status" == "error" ]; then
              echo "Deployment failed!"
              exit 1
            fi
            
            # Get the latest log messages
            log=$(curl -s -H "Authorization: Bearer ${{ secrets.NETLIFY_ACCESS_TOKEN }}" https://api.netlify.com/api/v1/deploys/$deploy_id/log)
            echo "$log" | tail -n 5
            
            sleep 10
          done

      - name: Get Full Netlify Deploy Log
        run: |
          curl -H "Authorization: Bearer ${{ secrets.NETLIFY_ACCESS_TOKEN }}" https://api.netlify.com/api/v1/deploys/$deploy_id/log > netlify_deploy_log.txt

      - name: Upload Netlify Deploy Log
        uses: actions/upload-artifact@v2
        with:
          name: netlify-deploy-log
          path: netlify_deploy_log.txt
